# Generated by Django 3.2 on 2021-09-09 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_alter_notice_writedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='writeDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 2, 11, 19, 24781), editable=False),
        ),
    ]
